master:
  name: 
  api_key: sa1t1c8gddb98915
  api_secret: oy3g5o1h84wlbrz77nmsrgcwrc9vphzh
  access_token: ""  # Keep blank if using TOTP login
  totp_key: ""       # Optional: required for auto-login
  email: ""
  mobile: ""
  enabled: true
  multiplier: 1.0

child_accounts:
  - name: 
    api_key: 
    api_secret: 
    access_token: ""
    totp_key: ""
    email: ""
    mobile: ""
    enabled: true
    multiplier: 1.0

capital_per_trade: 30000
stoploss_percent: 5
target_percent: 10
trail_sl_percent: 5

copy_trading: true
trading_enabled: true
