master:
  name: ZS1234
  api_key: sa1t1c8gddb98915
  api_secret: oy3g5o1h84wlbrz77nmsrgcwrc9vphzh
  access_token: ""
  enabled: true
  multiplier: 1.0

capital_per_trade: 30000
stoploss_percent: 5
target_percent: 10
trail_sl_percent: 5

copy_trading: true
trading_enabled: true

child_accounts: []



