master:
  name: "BL1330"
  api_key: "sa1t1c8gddb98915"
  api_secret: "oy3g5o1h84wlbrz77nmsrgcwrc9vphzh"
  access_token: ""  # Auto-populated after login
  totp_key: ""      # Optional: Add TOTP for auto-login
  email: ""
  mobile: ""
  enabled: true
  multiplier: 1.0
  last_login: ""

child_accounts:
  - name: "CHILD1"
    api_key: ""
    api_secret: ""
    access_token: ""
    totp_key: ""
    email: ""
    mobile: ""
    enabled: true
    multiplier: 1.0
    last_login: ""

  - name: "CHILD2"
    api_key: ""
    api_secret: ""
    access_token: ""
    totp_key: ""
    email: ""
    mobile: ""
    enabled: true
    multiplier: 0.5
    last_login: ""

trade_settings:
  capital_per_trade: 30000
  stoploss_percent: 5
  target_percent: 10
  trail_sl_percent: 5

features:
  copy_trading: true
  trading_enabled: true

app_settings:
  timezone: "Asia/Kolkata"
  webhook_auth:
    username: "webhookuser"
    password: "webhookpass"
