master:
  name: master
  api_key: your_master_api_key
  access_token: your_master_access_token

child_accounts:
  - name: child1
    api_key: your_child1_api_key
    access_token: your_child1_access_token

  - name: child2
    api_key: your_child2_api_key
    access_token: your_child2_access_token
