master:
  name: master
  access_token: H9r0loxwWCnVHkqASD2pVE5blGHpwOxe
  api_key: sa1t1c8gddb98915
  api_secret: oy3g5o1h84wlbrz77nmsrgcwrc9vphzh
  enabled: true
  multiplier: 1.0

capital_per_trade: 30000
stoploss_percent: 5
target_percent: 10
trail_sl_percent: 5

child_accounts:
  - name: child1
    api_key: your_child1_api_key
    access_token: ''
    api_secret: your_child1_api_secret
    enabled: true
    multiplier: 1.0

  - name: child2
    api_key: your_child2_api_key
    access_token: ''
    api_secret: your_child2_api_secret
    enabled: true
    multiplier: 1.0

  - name: child3
    api_key: your_child3_api_key
    access_token: ''
    api_secret: your_child3_api_secret
    enabled: true
    multiplier: 1.0

  - name: child4
    api_key: your_child4_api_key
    access_token: ''
    api_secret: your_child4_api_secret
    enabled: true
    multiplier: 1.0

  - name: child5
    api_key: your_child5_api_key
    access_token: ''
    api_secret: your_child5_api_secret
    enabled: true
    multiplier: 1.0

  - name: child6
    api_key: your_child6_api_key
    access_token: ''
    api_secret: your_child6_api_secret
    enabled: true
    multiplier: 1.0

  - name: child7
    api_key: your_child7_api_key
    access_token: ''
    api_secret: your_child7_api_secret
    enabled: true
    multiplier: 1.0
